### ISSUE TITLE
Uncaught Error: Cannot find module 'pos/components/pikaday-input

### ISSUE THREAD

**Issue by papakay** [adopted-ember-addons/ember-pikaday#196]
Please i'm having issue getting this to work with Ember 3.4.0

I got this error

```Uncaught Error: Cannot find module 'spentary-rxstore/components/pikaday-input```

**Comment by alexlafroscia** [comment]
Are you still seeing this issue?

If so, can you tell me what version of the `ember-cli` you are using?

**Comment by papakay** [comment]
I'm using Ember cli 3.3.0. I've decided to go for another option (Ember Flatpickr)

Thanks.

**Comment by mhankus** [comment]
I've had the same issue, but 2.2.6 works fine.

**Comment by alexlafroscia** [comment]
Interesting -- @papakay if you could check the `2.2.6` release as well (even though I know you've moved to a different addon instead) I would really appreciate it, just to see if this is something I still need to investigate.

**Comment by alexlafroscia** [comment]
Since @mhankus says this is fixed in the latest release, I’m going to close this. 

@papakay please let me know if the latest release does not, in fact, fix the issue!
